/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;
import java.util.ArrayList;
import java.util.List;

public class App {
    public App() {
        //following the warmup structure
    }
//This code is recycled from the App.java that was found in the warmup section with some key major changes
    public Object[] flatten(Object[] nested) { //we not are not taking in a nested array but rather one array because test 2 needs one array
        List<Object> result = new ArrayList<>(); //for final comparison

        for (Object item : nested) { //for each item in the list/array given.
            if (item instanceof String) { 
                String str = (String) item;
                if (str.length() > 1) {
                    result.add(str.substring(1));
                }
            }
        }

        return result.toArray(new Object[0]);
    }        
}
