/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;
import java.util.*;
import java.util.ArrayList;
import java.util.List;

import sdp.prac2.SimpleFunctions;

public class App {
    public App() {
        // No setup needed
    }

    public Object[] flatten(Object[] nested) {
        List<Object> result = new ArrayList<>();

        for (Object item : nested) {
            if (item instanceof String) {
                String str = (String) item;
                if (str.length() > 1) {
                    result.add(str.substring(1));
                }
            }
        }

        return result.toArray(new Object[0]);
    }        
}
