/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import java.util.ArrayList;
import java.util.List;

public class App {
    public App() {
        // Following the warm-up structure
    }

    // Task 2: Flatten method
    public Object[] flatten(Object[] nested) { 
        List<Object> result = new ArrayList<>(); // Store final comparison results

        for (Object item : nested) { // Iterate over each item in the array
            if (item instanceof String) { 
                String str = (String) item;
                if (str.length() > 1) {
                    result.add(str.substring(1)); // Remove first character
                }
            }
        }
        return result.toArray(new Object[0]);
    }    

    // Task 3: Validate balanced parentheses
    public static boolean Task3(String input) {
        int count = 0;

        for (char c : input.toCharArray()) {
            if (c == '(') {
                count++;
            } else if (c == ')') {
                count--;
                if (count < 0) {
                    return false; // More closing than opening parentheses
                }
            }
        }
        return count == 0; // Must be zero if perfectly matched
    }
}
